package arida.ufc.br.moap.network.mobnet.gui;
///*
// * To change this template, choose Tools | Templates
// * and open the template in the editor.
// */
//
///*
// * NewApplication.java
// *
// * Created on Nov 28, 2011, 11:18:19 AM
// */
//package arida.ufc.br.mobnet;
//
//
//import arida.ufc.br.dbmanager.DBManager;
//import arida.ufc.br.mobnet.frames.AboutFrame;
////import arida.ufc.br.mobnet.frames.CommunityDetectionFrame;
////import arida.ufc.br.mobnet.frames.CommunityViewFrame;
//import arida.ufc.br.mobnet.frames.NetworkManagerFrame;
////import arida.ufc.br.mobnet.frames.NetworkViewFrame;
////import arida.ufc.br.mobnet.frames.PoiNetworkBuilderFrame;
////import arida.ufc.br.mobnet.frames.TrajectoryNetworkBuilderFrame;
////import arida.ufc.br.mobnet.frames.TrajectoryViewFrame;
//import arida.ufc.br.mobnet.renderer.MapRenderer;
//import java.io.IOException;
//import java.sql.SQLException;
//import javax.swing.JOptionPane;
////import org.jdesktop.application.Action;
//
///**
// *
// * @author igobrilhante
// */
//public class MobNet extends javax.swing.JFrame {
//
//    /**
//	 * 
//	 */
//	private static final long serialVersionUID = -580458955954247847L;
//	/** Creates new form NewApplication */
////    protected static List<Painter<JXMapViewer>>
//    public MobNet() {
//        this.setTitle("MobNet");
//            initComponents();
////            jXTree1 = new JXTree();
////            jXMapKit1 = MapRenderer.getInstance().getMap();
////            try {
////                DBManager.getInstance();
////            }
////            catch (SQLException ex) {
////                JOptionPane.showMessageDialog(this, ex.getLocalizedMessage(),"Message",JOptionPane.ERROR_MESSAGE);
////                System.exit(0);
////            }
////            catch (IOException ex) {
////                JOptionPane.showMessageDialog(this, ex.getLocalizedMessage(),"Message",JOptionPane.ERROR_MESSAGE);
////                System.exit(0);
////            }
////            catch (ClassNotFoundException ex) {
////                JOptionPane.showMessageDialog(this, ex.getLocalizedMessage(),"Message",JOptionPane.ERROR_MESSAGE);
////                 System.exit(0);
////            }
//    }
//
//    /** This method is called from within the constructor to
//     * initialize the form.
//     * WARNING: Do NOT modify this code. The content of this method is
//     * always regenerated by the Form Editor.
//     */
//    @SuppressWarnings("unchecked")
//    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
//    private void initComponents() {
//
//        jXFrame1 = new org.jdesktop.swingx.JXFrame();
//        jXFrame2 = new org.jdesktop.swingx.JXFrame();
//        jXMapKit1 = MapRenderer.getInstance().getMap();
//        menuBar = new javax.swing.JMenuBar();
//        jMenu6 = new javax.swing.JMenu();
//        jMenuItem8 = new javax.swing.JMenuItem();
//        jMenu4 = new javax.swing.JMenu();
//        jMenuItem4 = new javax.swing.JMenuItem();
//        jMenu2 = new javax.swing.JMenu();
//        jMenuItem5 = new javax.swing.JMenuItem();
//        jMenu5 = new javax.swing.JMenu();
//        jMenuItem3 = new javax.swing.JMenuItem();
//        jMenu3 = new javax.swing.JMenu();
//        jMenuItem6 = new javax.swing.JMenuItem();
//        jMenuItem7 = new javax.swing.JMenuItem();
//        jMenu1 = new javax.swing.JMenu();
//        jMenuItem1 = new javax.swing.JMenuItem();
//        jMenuItem2 = new javax.swing.JMenuItem();
//
//        jXFrame1.setName("jXFrame1"); // NOI18N
//
//        org.jdesktop.layout.GroupLayout jXFrame1Layout = new org.jdesktop.layout.GroupLayout(jXFrame1.getContentPane());
//        jXFrame1.getContentPane().setLayout(jXFrame1Layout);
//        jXFrame1Layout.setHorizontalGroup(
//            jXFrame1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
//            .add(0, 400, Short.MAX_VALUE)
//        );
//        jXFrame1Layout.setVerticalGroup(
//            jXFrame1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
//            .add(0, 300, Short.MAX_VALUE)
//        );
//
//        jXFrame2.setName("jXFrame2"); // NOI18N
//
//        org.jdesktop.layout.GroupLayout jXFrame2Layout = new org.jdesktop.layout.GroupLayout(jXFrame2.getContentPane());
//        jXFrame2.getContentPane().setLayout(jXFrame2Layout);
//        jXFrame2Layout.setHorizontalGroup(
//            jXFrame2Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
//            .add(0, 400, Short.MAX_VALUE)
//        );
//        jXFrame2Layout.setVerticalGroup(
//            jXFrame2Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
//            .add(0, 300, Short.MAX_VALUE)
//        );
//
//        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
//        setName("Form"); // NOI18N
//
//        jXMapKit1.setDefaultProvider(org.jdesktop.swingx.JXMapKit.DefaultProviders.OpenStreetMaps);
//        jXMapKit1.setName("jXMapKit1"); // NOI18N
//
//        menuBar.setName("menuBar"); // NOI18N
//
//        jMenu6.setText("MobNet");
//        jMenu6.setName("jMenu6"); // NOI18N
//
////        javax.swing.ActionMap actionMap = org.jdesktop.application.Application.getInstance().getContext().getActionMap(MobNet.class, this);
////        jMenuItem8.setAction(actionMap.get("aboutAction")); // NOI18N
//        jMenuItem8.setText("About MobNet");
//        jMenuItem8.setName("jMenuItem8"); // NOI18N
//        jMenu6.add(jMenuItem8);
//
//        menuBar.add(jMenu6);
//
//        jMenu4.setText(org.openide.util.NbBundle.getMessage(MobNet.class, "MobNet.jMenu4.text")); // NOI18N
//        jMenu4.setName("jMenu4"); // NOI18N
//
////        jMenuItem4.setAction(actionMap.get("networkManagerAction")); // NOI18N
//        jMenuItem4.setText(org.openide.util.NbBundle.getMessage(MobNet.class, "MobNet.jMenuItem4.text")); // NOI18N
//        jMenuItem4.setName("jMenuItem4"); // NOI18N
//        jMenu4.add(jMenuItem4);
//
//        menuBar.add(jMenu4);
//
//        jMenu2.setText(org.openide.util.NbBundle.getMessage(MobNet.class, "MobNet.jMenu2.text")); // NOI18N
//        jMenu2.setName("jMenu2"); // NOI18N
//
////        jMenuItem5.setAction(actionMap.get("trajectoryNetworkBuilderAction")); // NOI18N
//        jMenuItem5.setText(org.openide.util.NbBundle.getMessage(MobNet.class, "MobNet.jMenuItem5.text")); // NOI18N
//        jMenuItem5.setName("jMenuItem5"); // NOI18N
//        jMenu2.add(jMenuItem5);
//
//        jMenu5.setText(org.openide.util.NbBundle.getMessage(MobNet.class, "MobNet.jMenu5.text")); // NOI18N
//        jMenu5.setName("jMenu5"); // NOI18N
//
////        jMenuItem3.setAction(actionMap.get("trajectoryViewAction")); // NOI18N
//        jMenuItem3.setText(org.openide.util.NbBundle.getMessage(MobNet.class, "MobNet.jMenuItem3.text")); // NOI18N
//        jMenuItem3.setName("jMenuItem3"); // NOI18N
//        jMenu5.add(jMenuItem3);
//
//        jMenu2.add(jMenu5);
//
//        menuBar.add(jMenu2);
//
////        jMenu3.setAction(actionMap.get("communityDetection")); // NOI18N
////        jMenu3.setText(org.openide.util.NbBundle.getMessage(MobNet.class, "MobNet.jMenu3.text")); // NOI18N
////        jMenu3.setName("jMenu3"); // NOI18N
////
////        jMenuItem6.setAction(actionMap.get("poiNetworkBuilderAction")); // NOI18N
////        jMenuItem6.setText(org.openide.util.NbBundle.getMessage(MobNet.class, "MobNet.jMenuItem6.text")); // NOI18N
////        jMenuItem6.setName("jMenuItem6"); // NOI18N
////        jMenu3.add(jMenuItem6);
////
////        jMenuItem7.setAction(actionMap.get("communityDetectionAction")); // NOI18N
////        jMenuItem7.setText(org.openide.util.NbBundle.getMessage(MobNet.class, "MobNet.jMenuItem7.text")); // NOI18N
////        jMenuItem7.setName("jMenuItem7"); // NOI18N
////        jMenu3.add(jMenuItem7);
////
////        jMenu1.setAction(actionMap.get("communityViewAction")); // NOI18N
////        jMenu1.setText(org.openide.util.NbBundle.getMessage(MobNet.class, "MobNet.jMenu1.text")); // NOI18N
////        jMenu1.setToolTipText(org.openide.util.NbBundle.getMessage(MobNet.class, "MobNet.jMenu1.toolTipText")); // NOI18N
////        jMenu1.setName("jMenu1"); // NOI18N
////
////        jMenuItem1.setAction(actionMap.get("networkView")); // NOI18N
////        jMenuItem1.setText(org.openide.util.NbBundle.getMessage(MobNet.class, "MobNet.jMenuItem1.text")); // NOI18N
////        jMenuItem1.setToolTipText(org.openide.util.NbBundle.getMessage(MobNet.class, "MobNet.jMenuItem1.toolTipText")); // NOI18N
////        jMenuItem1.setName("jMenuItem1"); // NOI18N
////        jMenu1.add(jMenuItem1);
////
////        jMenuItem2.setAction(actionMap.get("communityViewAction")); // NOI18N
////        jMenuItem2.setText(org.openide.util.NbBundle.getMessage(MobNet.class, "MobNet.jMenuItem2.text")); // NOI18N
////        jMenuItem2.setToolTipText(org.openide.util.NbBundle.getMessage(MobNet.class, "MobNet.jMenuItem2.toolTipText")); // NOI18N
////        jMenuItem2.setName("jMenuItem2"); // NOI18N
////        jMenu1.add(jMenuItem2);
//
//        jMenu3.add(jMenu1);
//
//        menuBar.add(jMenu3);
//
//        setJMenuBar(menuBar);
//
//        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(getContentPane());
//        getContentPane().setLayout(layout);
//        layout.setHorizontalGroup(
//            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
//            .add(jXMapKit1, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 881, Short.MAX_VALUE)
//        );
//        layout.setVerticalGroup(
//            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
//            .add(jXMapKit1, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 526, Short.MAX_VALUE)
//        );
//
//        pack();
//    }// </editor-fold>//GEN-END:initComponents
//
//    /**
//     * @param args the command line arguments
//     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        }
//
//
//
//        catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(MobNet.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }        catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(MobNet.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }        catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(MobNet.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }        catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(MobNet.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//
//            public void run() {
//                new MobNet().setVisible(true);
//
//            }
//        });
//    }
//    
////    @Action
////    public void networkFrameAction() {
////        java.awt.EventQueue.invokeLater(new Runnable() {
////
////            public void run() {
////                networkFrame = new NetworkManagerFrame();
////                networkFrame.setVisible(true);
////            }
////        });
////
////    }
//
////    @Action
////    public void communityViewAction() {
////        java.awt.EventQueue.invokeLater(new Runnable() {
////
////            public void run() {
////                System.out.println("Community View");
////                if (communityViewFrame == null) {
////                    communityViewFrame = new CommunityViewFrame();
////                    
////                }
////
////                communityViewFrame.setVisible(true);
////            }
////        });
////
////    }
////
////    @Action
////    public void networkViewAction() {
////        java.awt.EventQueue.invokeLater(new Runnable() {
////
////            public void run() {
////                if (networkViewFrame == null) {
////                    networkViewFrame = new NetworkViewFrame();
//////            this.add(networkViewPanel);
//////            this.repaint();
////                    System.out.println("Network View");
////                }
////
////                networkViewFrame.setVisible(true);
////            }
////        });
////
////    }
////
////    @Action
////    public void communityDetectionAction() {
////        java.awt.EventQueue.invokeLater(new Runnable() {
////
////            public void run() {
////                CommunityDetectionFrame communityDetectionFrame = new CommunityDetectionFrame();
////                communityDetectionFrame.setVisible(true);
////            }
////        });
////    }
////
////    @Action
////    public void networkManagerAction() {
////        java.awt.EventQueue.invokeLater(new Runnable() {
////
////            public void run() {
////                NetworkManagerFrame networkManagerFrame = new NetworkManagerFrame();
////                networkManagerFrame.setVisible(true);
////            }
////        });
////    }
////
////    @Action
////    public void poiNetworkBuilderAction() {
////         java.awt.EventQueue.invokeLater(new Runnable() {
////
////            public void run() {
////                PoiNetworkBuilderFrame poiNetworkBuilderFrame = new PoiNetworkBuilderFrame();
////                poiNetworkBuilderFrame.setVisible(true);
////            }
////        });
////    }
////
////    @Action
////    public void trajectoryNetworkBuilderAction() {
////        java.awt.EventQueue.invokeLater(new Runnable() {
////
////            public void run() {
////                TrajectoryNetworkBuilderFrame tnf = new TrajectoryNetworkBuilderFrame();
////                tnf.setVisible(true);
////            }
////        });
////    }
////
////    @Action
////    public void trajectoryViewAction() {
////        java.awt.EventQueue.invokeLater(new Runnable() {
////
////            public void run() {
////                TrajectoryViewFrame tvf = new TrajectoryViewFrame();
////                tvf.setVisible(true);
////            }
////        });
////    }
////
////    @Action
////    public void aboutAction() {
////         java.awt.EventQueue.invokeLater(new Runnable() {
////
////            public void run() {
////                AboutFrame about = new AboutFrame();
////                about.setVisible(true);
////            }
////        });
////    }
//    // Variables declaration - do not modify//GEN-BEGIN:variables
//    private javax.swing.JMenu jMenu1;
//    private javax.swing.JMenu jMenu2;
//    private javax.swing.JMenu jMenu3;
//    private javax.swing.JMenu jMenu4;
//    private javax.swing.JMenu jMenu5;
//    private javax.swing.JMenu jMenu6;
//    private javax.swing.JMenuItem jMenuItem1;
//    private javax.swing.JMenuItem jMenuItem2;
//    private javax.swing.JMenuItem jMenuItem3;
//    private javax.swing.JMenuItem jMenuItem4;
//    private javax.swing.JMenuItem jMenuItem5;
//    private javax.swing.JMenuItem jMenuItem6;
//    private javax.swing.JMenuItem jMenuItem7;
//    private javax.swing.JMenuItem jMenuItem8;
//    private org.jdesktop.swingx.JXFrame jXFrame1;
//    private org.jdesktop.swingx.JXFrame jXFrame2;
//    private org.jdesktop.swingx.JXMapKit jXMapKit1;
//    private javax.swing.JMenuBar menuBar;
//    // End of variables declaration//GEN-END:variables
////    private CommunityViewFrame communityViewFrame = null;
////    private NetworkViewFrame networkViewFrame = null;
//    private NetworkManagerFrame networkFrame = null;
//}
